application: sos-beacon-dev
version: 5
runtime: python27
api_version: 1
threadsafe: true

skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (\..*)|
 (lib/local/.*)|
 (.idea)|
 (.ropeproject)|
 (.git)|
 (.gitignore)|
 (assets)|
 )$


libraries:
- name: webob
  version: latest
- name: markupsafe
  version: latest

builtins:
- appstats: on
- remote_api: on

admin_console:
  pages:
  - name: Appstats
    url: /_ah/stats/

handlers:
- url: /crossdomain.xml
  static_files: static/crossdomain.xml
  upload: static/crossdomain.xml
  mime_type: text/xml

- url: /audiojs.swf
  static_files: static/script/audiojs.swf
  upload: static/script/audiojs.swf

- url: /player-graphics.gif
  static_files: static/script/player-graphics.gif
  upload: static/script/player-graphics.gif

- url: /static
  static_dir: static

- url: /authentication.*
  script: login.app

- url: /admin/authentication.*
  script: login.app

- url: /_ah/login_required
  script: login_openid.app

- url: /_userconfig.*
  script: login_openid.app
  login: required

- url: /uploads/view/.*
  script: main.app

- url: /service/message.*
  script: service.app

- url: /service/.*
  script: service.app
#  login: required

- url: /task/.*
  script: task.app
  login: admin

- url: /shell/static
  static_dir: shell/static
  expiration: 1d
  login: admin

- url: /shell/.*
  script: shell.shell.application
  login: admin

- url: /e/.*
  script: main.app

- url: .*
  script: main.app
#  login: required

